- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-hos
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: BoxFolderBlack
    pocket2: PenCentcom

- type: job
  id: InternalAffairsAgent
  name: job-name-iaa
  description: job-description-iaa
  playTimeTracker: JobInternalAffairsAgent
  requirements:
    - !type:RoleTimeRequirement
      role: JobCaptain
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 1620000 # 45 hours
  setPreference: true
  requireAdminNotify: true
  weight: 20
  startingGear: InternalAffairsAgentGear
  icon: "JobIconInternalAffairsAgent"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Brig
  - InternalAffairs
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: InternalAffairsAgentGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomAgent
    back: ClothingBackpackCentcomInspectorFilled
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    belt: BoxFolderCentComClipboard
    id: CentcomInspectorPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: PenCentcom
    pocket2: BoxFolderGreen
  inhand:
    - BriefcaseBrownFilled
  satchel: ClothingBackpackSatchelCentcomInspectorFilled
  duffelbag: ClothingBackpackDuffelCentcomInspectorFilled
